// Generated by `wit-bindgen` 0.37.0. DO NOT EDIT!
#include "nux.h"
#include <stdlib.h>

// Imported Functions from `nux`

__attribute__((__import_module__("$root"), __import_name__("get-position")))
extern int32_t __wasm_import_nux_get_position(void);

__attribute__((__import_module__("$root"), __import_name__("set-position")))
extern void __wasm_import_nux_set_position(int32_t);

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Component Adapters

uint32_t nux_get_position(void) {
  int32_t ret = __wasm_import_nux_get_position();
  return (uint32_t) (ret);
}

void nux_set_position(uint32_t pos) {
  __wasm_import_nux_set_position((int32_t) (pos));
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_nux(void);
void __component_type_object_force_link_nux_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_nux();
}
