// Generated by `wit-bindgen` 0.37.0. DO NOT EDIT!
#ifndef __BINDINGS_NUX_H
#define __BINDINGS_NUX_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

// Imported Functions from `nux`
extern uint32_t nux_get_position(void);
extern void nux_set_position(uint32_t pos);

#ifdef __cplusplus
}
#endif
#endif
